/**
 * Build zone lookup data from USPS zone chart markdown files.
 *
 * Run: npx tsx scripts/build_zone_lookup.ts
 * Output: lib/zone-chart-data.ts (compact static lookup for 3 warehouses)
 */

import * as fs from 'fs';
import * as path from 'path';

const VAULT_BASE = path.join(
  process.env.HOME!,
  'Library/Mobile Documents/com~apple~CloudDocs/obsidian/shippingcow.ai/data'
);

const WAREHOUSE_FILES: Record<string, string> = {
  '089': 'zone_chart_NJ_089.md',
  '917': 'zone_chart_CA_917.md',
  '774': 'zone_chart_TX_774.md',
};

/**
 * Parse a zone chart markdown table into a Map<dest_prefix, zone>
 */
function parseZoneChart(filePath: string): Map<string, number> {
  const content = fs.readFileSync(filePath, 'utf-8');
  const lines = content.split('\n');
  const map = new Map<string, number>();

  let inTable = false;
  for (const line of lines) {
    const trimmed = line.trim();

    // Detect table start
    if (trimmed.startsWith('| origin_prefix | dest_prefix | zone |')) {
      inTable = true;
      continue;
    }
    // Skip separator row
    if (trimmed.startsWith('|---|---|---|')) continue;
    if (!inTable) continue;
    if (trimmed === '' || !trimmed.startsWith('|')) {
      // End of table on non-table row
      continue;
    }

    const parts = trimmed.split('|').map(p => p.trim());
    if (parts.length >= 4) {
      const destPrefix = parts[2];
      const zone = parseInt(parts[3], 10);
      if (!isNaN(zone) && destPrefix.length === 3) {
        map.set(destPrefix, zone);
      }
    }
  }

  return map;
}

// Build the lookup
const zoneLookup: Record<string, Record<string, number>> = {};

for (const [prefix, filename] of Object.entries(WAREHOUSE_FILES)) {
  const filePath = path.join(VAULT_BASE, filename);
  if (!fs.existsSync(filePath)) {
    console.error(`File not found: ${filePath}`);
    process.exit(1);
  }
  const chart = parseZoneChart(filePath);
  zoneLookup[prefix] = Object.fromEntries(chart);
  console.log(`${prefix}: ${chart.size} destination prefixes loaded`);
}

// Write TypeScript file
const tsContent = `// Auto-generated by scripts/build_zone_lookup.ts — DO NOT EDIT
// USPS Domestic Zone Chart for ShippingCow warehouses
// Maps origin_prefix -> { dest_prefix -> zone }
// Generated: ${new Date().toISOString()}

const ZONE_CHART: Record<string, Record<string, number>> = ${JSON.stringify(zoneLookup, null, 2)};

export function lookupZone(originPrefix: string, destPrefix: string): number | null {
  const origins = ZONE_CHART[originPrefix];
  if (!origins) return null;
  return origins[destPrefix] ?? null;
}

export default ZONE_CHART;
`;

const outputPath = path.join(process.cwd(), 'lib/zone-chart-data.ts');
fs.writeFileSync(outputPath, tsContent, 'utf-8');
console.log(`\nWritten ${outputPath}`);
console.log(`Total size: ${(Buffer.byteLength(tsContent) / 1024).toFixed(1)} KB`);
